version: '3.4'

services:
  apihubrprv4:
    image: apihubrprv4
    build:
      context: backend/node/src
      dockerfile: ../Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      APP_PORT: ${APP_PORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGUSER}
      PGPORT: ${PGPORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm start

  apihubpg:
    image: apihubpg
    build:
      context: backend/postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${PGPORT}:${PGPORT}
    restart: unless-stopped
