version: '3.4'

services:
  apihubrprv4:
    image: apihubrprv4
    build:
      context: backend/node/src
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm start

  apihubpg:
    image: apihubpg
    build:
      context: backend/postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${pg_usr}
      POSTGRES_PASSWORD: ${pg_pwd}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
